# Generated by Django 4.1 on 2022-10-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputForm',
        ),
    ]
