# Generated by Django 4.1 on 2022-10-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputModel',
        ),
    ]
