# Generated by Django 4.1 on 2022-10-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0006_inputmodel_text_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='text_msg',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
