# Generated by Django 4.1 on 2022-11-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0010_rename_user_id_inputmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmodel',
            name='user',
        ),
    ]
