# Generated by Django 4.1 on 2022-10-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='contenu',
            new_name='content',
        ),
    ]
